// <auto-generated />
namespace NET_FlatFileToDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class flatfiledbschemav10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(flatfiledbschemav10));
        
        string IMigrationMetadata.Id
        {
            get { return "201707030704414_flatfiledb schema v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
